{% set name = "mlxtend" %}
{% set version = "0.11.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6addc88f343e39fb775e44485a79b81f10de51a6ca4295101b2dc60feef466a6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.11.2
    - scipy >=0.18.1
    - scikit-learn >=0.18
    - pandas >=0.19.1
    - matplotlib >=1.5.1

test:
  requires:
    - nose
  imports:
    - mlxtend
    - mlxtend._base
    - mlxtend.classifier
    - mlxtend.cluster
    - mlxtend.data
    - mlxtend.evaluate
    - mlxtend.externals
    - mlxtend.feature_extraction
    - mlxtend.feature_selection
    - mlxtend.file_io
    - mlxtend.frequent_patterns
    - mlxtend.math
    - mlxtend.plotting
    - mlxtend.preprocessing
    - mlxtend.regressor
    - mlxtend.text
    - mlxtend.utils

about:
  home: https://github.com/rasbt/mlxtend
  license: BSD v3
  license_family: BSD
  license_file: LICENSE-BSD3.txt
  summary: Machine Learning Library Extensions
  description: >
    A library of Python tools and extensions for data science
    and machine learning.

    Contact
    =============

    If you have any questions or comments about mlxtend,
    please feel free to contact me via
    eMail: mail@sebastianraschka.com
    or Twitter: https://twitter.com/rasbt

    This project is hosted at https://github.com/rasbt/mlxtend
    The documentation can be found at http://rasbt.github.io/mlxtend/
  doc_url: 'http://rasbt.github.io/mlxtend/'
  dev_url: 'https://github.com/rasbt/mlxtend'

extra:
  recipe-maintainers:
    - rasbt
